### ISSUE TITLE
possible unit conversion bug

### ISSUE THREAD

**Issue by superbock** [mido/mido#102]
I am not completely sure, since I am by no means an expert for MIDI, but I think your conversion between bpm and tempo (i.e. `bpm2tempo` and `tempo2bpm`) does not take the time signature into account.

If I am correct, MIDI usually refers to the tempo in ticks per quarter note. Thus depending on the time signature, the duration of a beat may vary. The functions work only correctly for 4/4 time signature.

__Edit:__ updated the issue with a description, the initial issue was empty. Sorry.
__Edit 2:__ I think the same problem exists in all unit conversions in `midifiles.units`.

**Comment by olemb** [comment]
Hi Sebastian,

Apologies for the late reply. I've been in vacation.

MIDI tempo is defined by microseconds per beat (quarter note). Time signature should not factor in as a beat has the same length in any time signature. For example a 2/4 measure would last half as long as the 4/4 measure. (2 beats vs. 4 beats.) Odd signatures like 2/3 are a bit trickier to compute but should also be based on the length of a quarter note.

I may be wrong though. Do you have an example of a time signature where this is not correct?

**Comment by superbock** [comment]
Hi Ole, 

Yes, MIDI tempo is in microseconds per quarter note and for the default time signature of 4/4 everything is just fine. You are also right that a 2/4 bar lasts half as long as a 4/4 measure since each bar contains a different number of beats (2 vs. 4) and each beat has the same duration (a quarter note)

The problem, however, is that this is only true for 4/4 time signature. If the denominator changes (btw. 2/3 is not possible in MIDI, since the denominator can only be a power of 2), this also changes the length of a beat. If it is a x/2 time signature each beat has the length of a half note, i.e. two quarter notes. Thus the conversion from beats (in bpm) to MIDI tempo (in ticks per quarter note) has to consider the denominator of the time signature. At least this is my (sowmhow limited) knowledge about MIDI tempo, but it matches [this answers on music.stackexchange.com](https://music.stackexchange.com/a/24145).

I added updated versions of unit conversions [to my code](https://github.com/CPJKU/madmom/pull/308/files#diff-c50455c4f06264e1275f413634df9d71R19) so you can have a look at them. The updated unit conversion functions also required a fix to `mido.MidiFile.__iter__` in order to consider the time signature events (similar to the handling of tempo events). My `MIDIFile` class inherits from `mido.MidiFile` and contains this fix as well. I am happy to provide a PR with those fixes.

As a side note (but this should possibly go into a new issue), my `MIDIFile` class contains a couple of other enhancements. This includes conversion from/to NumPy array representations of the notes which is used in the doctest examples. The updated `__iter__` method is also able to handle different units (seconds, ticks, beats) and relative/absolute timing of the events transparently. I think this would make a nice addition to mido as well. If you think so too, please let me know.

**Comment by olemb** [comment]
Ah, thanks for the explanation! I wasn't aware of this.

I'd be happy to merge your functions if you send me a pull request. One thing though: should they have aa default value of `(4, 4)` for `time_signature`? This would make them backwards compatible and also make them easier to use if you don't care about time signatures. (Basically, if you always use 4/4.)

Your improved `MidiFile` class sounds useful. I haven't had a chance to look at it yet but it's definitely interesting. I know there are lots of people using Mido with NumPy. Could you make a new issue?

**Comment by superbock** [comment]
I will send a PR with the fixes for the the unit conversion functions as soon as I have time to do so.

**Comment by rdoursenaud** [comment]
I consider the bug fixed by #114 and will thus close this issue.

Feel free to reopen if you think that's not the case.
