### ISSUE TITLE
Message and MetaMessage

### ISSUE THREAD

**Issue by Nintorac** [mido/mido#146]
I was wondering what the motivation was behind the different layouts of these two classes.

I like the Message way of doing things where spec is defined in a seperate file and is accesible as a dictionary, this allows me to get a list of the values associated with the Message, unfortunately since MetaMessage uses a class as the spec this is not possible.

Since they are all Messages would it not make more sense to have a MidiMessage class and MetaMessage class which both subclass a Message type?

Cheers

**Comment by rdoursenaud** [comment]
Please see: https://github.com/mido/mido/issues/82#issuecomment-1410121347
