### ISSUE TITLE
3 new features?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [mido/mido#154]
I've added 2 new features to my `mido `superclass of the `MidiFile `object.

They are:
* Tempo
* Clock error recovery

* Volume - A third I did outside the class

The volume I implemented outside the class, after I read the message.  That code can be easily brought into the `MidiFile `class just like the tempo feature was.

All of these are/will be limited to the `MidiFile `object.  I was wandering if the mido team is at all interested in seeing the changes.  I don't really want to take the time to integrate into something official if it's gonna get bounced, thus wasting my time and perhaps others time.

**Comment by MikeTheWatchGuy** [comment]
It's been over 8 months.  I don't recall what the problem was.  You can close this issue.

**Comment by rdoursenaud** [comment]
The next time you can make a draft pull-request.
I'd be interested to look at the way you implemented these.
