### ISSUE TITLE
smpte_offset frame rate at 25fps 

### ISSUE THREAD

**Issue by laori93** [mido/mido#156]
Hi, I having some problem here with a frame rate set at 25.
My goal is to generate a midi file with markers that I can import in my daw (Pro tools).
With a frame rate set at 24fps PT recognize it at 24fps.
With a frame rate set at 25fps PT recognize a 30DF frame rate...
Value of smpte_offset @24 is: 0:0:0:0:0
Value of smpte_offset @25 is: 64:0:0:0:0  (shouldn't it be 32:0:0:0:0 ?)
Sorry if this is a dumb question, I'm quite a newbie.
Thanks anyway for your great work !

![25fps_offset](https://user-images.githubusercontent.com/37245281/37243642-35afa742-247d-11e8-86f7-5e41ba72c2e5.png)

**Comment by laori93** [comment]
I found out a workaround.
I replace one byte in midi file generated with Mido. ('40' to '20' at address 0x1a.)

`with file('Mido_25.mid', 'r+b') as fh:
    fh.seek(0x1a)
    fh.write(b'\x20')`

See the problematic midi file (@25fps) in attachment and the corrected one.
Try to import in Protools both of them and check Session Setup...
I was able to find out a solution comparing with a midi file generated with Edimarker (free app that does the same job but only one file at a time.)
[midifiles.zip](https://github.com/olemb/mido/files/1997690/midifiles.zip)

Have a good day !

**Comment by heilei** [comment]
It seems that Mido also interprets both SMPTE hour and frame rate incorrectly, when parsing meta messages from a MIDI file. According to the MIDI file standard, these two values are encoded into one byte in the SMPTE Offset meta message: first bit is zero, the next two bits are the coded frame rate, and the remaining 5 bits are SMPTE hour. Mido seems to always parse these values as 25 FPS and 33 hours, which are incorrect (SMPTE hours should be between 0 and 23 hours).

**Comment by heilei** [comment]
As an example, for a MIDI file with frame rate 30 fps, Mido message parser gives this:

<meta message smpte_offset frame_rate=25 hours=33 minutes=0 seconds=0 frames=0 sub_frames=0 time=0>

**Comment by heilei** [comment]
As an example, for a MIDI file with a frame rate of 30 fps, Mido parser returns this:

meta message smpte_offset frame_rate=25 hours=33 minutes=0 seconds=0 frames=0 sub_frames=0 time=0

**Comment by heilei** [comment]
The bug seems to be in class MetaSpec_smpte_offset(MetaSpec):

	def decode(self, message, data):
		message.frame_rate = _smpte_framerate_decode[(data[0] >> 6)]
		...

	def encode(self, message):
		frame_rate_lookup = _smpte_framerate_encode[message.frame_rate] << 6
		...

The bit shifts above should be 5 bits, not 6.
