### ISSUE TITLE
Message comparison is broken

### ISSUE THREAD

**Issue by belm0** [mido/mido#163]
Message implements only `__eq__`, so for example `msg_a == msg_b` and `msg_a != msg_b` can both yield `True`.

https://github.com/olemb/mido/blob/e87384d7e5d62de361a65ab6b1d5d62750475e84/mido/messages/messages.py#L68

https://www.python.org/dev/peps/pep-0008/#programming-recommendations
> When implementing ordering operations with rich comparisons, it is best to implement all six operations (__eq__, __ne__, __lt__, __le__, __gt__, __ge__) rather than relying on other code to only exercise a particular comparison.
>
> To minimize the effort involved, the functools.total_ordering() decorator provides a tool to generate missing comparison methods

**Comment by olemb** [comment]
How can they both be true at the same time?

I don't understand why there's a need to implement ordering methods (or at least one of them using `functools.total_ordering()` if there is no natural way to order messages (or tracks or MIDI files). Am I missing something?

**Comment by olemb** [comment]
Would it be enough to implement `ne` as `not eq` as suggested here?

https://stackoverflow.com/questions/4352244/should-i-implement-ne-as-the-negation-of-eq-in-python

**Comment by belm0** [comment]
I see, implementing `ne` is only required for Python 2.

It looks like the recommended solution is implement `ne` as `not self == other`.

https://stackoverflow.com/questions/4352244/should-i-implement-ne-as-the-negation-of-eq-in-python/30676267#30676267

**Comment by olemb** [comment]
OK, sounds good. We should implement `__ne__()` for Python 2 and mark it as something that can be removed when we drop Python 2 support.

**Comment by rdoursenaud** [comment]
We are dropping Python 2 support in the upcoming release.
I don't think this is relevant anymore.
Feel free to reopen if I'm mistaken!
