### ISSUE TITLE
merge_tracks crashes on unknown_meta message

### ISSUE THREAD

**Issue by mqnc** [mido/mido#197]
The error I get is this:
```
  File "...", line 14, in <module>
    allMsgs = mido.merge_tracks(midiin.tracks)
  File ".../mido/midifiles/tracks.py", line 104, in merge_tracks
    messages.extend(_to_abstime(track))
  File ".../mido/midifiles/tracks.py", line 62, in _to_abstime
    yield msg.copy(time=now)
  File ".../mido/midifiles/meta.py", line 509, in copy
    return self.__class__(**attrs)
```
and when I print the attrs variable (modifying meta.py before line 509), I get:
`{'type': 'unknown_meta', 'type_byte': 15, 'data': (...), 'time': 0}`

And the thing is that the __init__ of the UnknownMetaMessage class does not accept a type argument. I added the argument, it does nothing and now it works.

**Comment by rdoursenaud** [comment]
Should be fixed now that #286 is merged.
Feel free to reopen if not.
Thanks.
