### ISSUE TITLE
Runs fine in shell, not in script

### ISSUE THREAD

**Issue by samhorne** [mido/mido#203]
If I run the following code from the IDLE Python 3.6.2 Shell, typing the 6 lines one at a time, the MIDI note sends successfully. If I save these 6 lines of code in a .py file and run it from IDLE, the "Sent" prints, but the MIDI note does not send successfully.
What am I missing running this as a script?

`<import mido`
`msg = mido.Message('note_on', note=60)`
`msg.copy(channel=2)`
`port = mido.open_output(name='foo', virtual=True)`
`port.send(msg)`
`print('Sent')`

**Comment by jamd315** [comment]
The code looks mostly correct, but you're using `msg.copy` incorrectly, `msg.copy` returns a new message.  If you run the code above, it will send on channel 0 by default.  Try doing either `msg = msg.copy(channel=2)` or creating the Message with the channel parameter `msg = mido.Message('note_on', note=60, channel=2)` and skipping the `copy`.

**Comment by samhorne2** [comment]
Thanks for the info. For now, [simplecoremidi](https://github.com/sixohsix/simplecoremidi) seems to be working fine in a script.
