### ISSUE TITLE
Forum not working / Quantic music

### ISSUE THREAD

**Issue by rcaze** [mido/mido#220]
I wanted to post something on the forum around mido but the link does not work for me https://groups.google.com/forum/#!forum/mido-community (it says this group does not exist .or ..)

**Comment by xhevahir** [comment]
I just ran into this problem after closing an issue here. Has the Google Group been deactivated?

**Comment by olemb** [comment]
Thanks for letting us know about this.

It looks like a lot of people have problems accessing the Google group. For this and other reasons we've decided to close it down. (There have only been a few posts so far.)

I set up discussion page here on GitHub. Hopefully this will work better. Feel free to post there.

Here's my welcome message that I posted today: #257
