### ISSUE TITLE
naming a port

### ISSUE THREAD

**Issue by flok99** [mido/mido#222]
Using the ALSA C/C++ library you can name a midi in/out port:

snd_seq_set_client_name(seqhnd, "programname");
snd_seq_create_simple_port(seqhnd, "portname", SND_SEQ_PORT_CAP_READ | SND_SEQ_PORT_CAP_SUBS_READ, SND_SEQ_PORT_TYPE_MIDI_GENERIC | SND_SEQ_PORT_TYPE_APPLICATION))

It would be cool if this becomes possible in MIDO as well because currently we have names like 

128:0    RtMidiOut Client                 RtMidi output
129:0    RtMidiOut Client                 RtMidi output

**Comment by olemb** [comment]
You can do this in Mido:

    >>> port = mido.open_input('portname', client_name='programname')

The `client_name` part is a bit hidden since it's unique to the RtMidi backend, but here it is in the docs:

    https://mido.readthedocs.io/en/latest/backends/rtmidi.html#client-name

**Comment by flok99** [comment]
Thanks!!
