### ISSUE TITLE
Merge tracks from multiple MIDI files into one MIDI file

### ISSUE THREAD

**Issue by saatsochyaasi** [mido/mido#242]
I have midi files (type 1) from various instruments that are part of the same composition. How can I merge them all into a single midi file that would contain all the original midi files as separate tracks (not as single track when visualized in a DAW)? I tried the following approach, but I am getting `ValueError: message time must be int in MIDI file` at `merged_mid.save("test_merged")`. 

### What I tried:
```
for midi_file in names_midi_files:
    mid = mido.MidiFile("{}{}{}".format(path_data_files, os.path.sep, midi_file))
    mid_list.append(mid)
    
merged_track = mido.merge_tracks(mid_list)
merged_mid = mido.MidiFile(type=1)
merged_mid.tracks.append(merged_track)
merged_mid.save("test_merged")
```

### Output from `mid` and `merged_track`:
```
for msg_trk in mid.tracks[0]:
    print(msg_trk)
    
note_on channel=0 note=0 velocity=1 time=0
note_off channel=0 note=0 velocity=0 time=1
note_on channel=0 note=36 velocity=90 time=84479
note_off channel=0 note=36 velocity=90 time=3840
note_on channel=0 note=41 velocity=73 time=0
note_off channel=0 note=41 velocity=73 time=1920
note_on channel=0 note=46 velocity=84 time=0
note_off channel=0 note=46 velocity=84 time=1920
note_on channel=0 note=36 velocity=70 time=0
note_off channel=0 note=36 velocity=70 time=3840
<meta message end_of_track time=1>

for msg_merged_trk in merged_track:
    print(msg_merged_trk)

.
.
.
note_on channel=0 note=51 velocity=0 time=0.0
note_off channel=0 note=51 velocity=0 time=0.25
note_on channel=0 note=56 velocity=0 time=0.0
note_off channel=0 note=44 velocity=71 time=0.625
note_off channel=0 note=56 velocity=76 time=0.0
note_off channel=0 note=56 velocity=0 time=0.0
<meta message end_of_track time=0.00104166666667>
```

I think [this ](https://github.com/VirtuosicAI/MIDI-Merger-Lite) program can do what I am trying to do, but I don't know how to install that program.

**Comment by olemb** [comment]
Would this work?

```python
mid1 = MidiFile('first.mid')
mid2 = MidiFile('second.mid')

merged_mid = MidiFile()
# Copy time resolution. (If mid1 and mid2 have different
# ticks_per_beat you will get timing problems.)
merged_mid.ticks_per_beat=mid1.ticks_per_beat

merged_mid.tracks = mid1.tracks + mid2.tracks
merged_mid.save('merged.mid')
```

**Comment by saatsochyaasi** [comment]
@olemb 
It just makes a single track, whereas I want each midi file as a separate track. For example, Track 1 and Track 2 are two midi files (say midi1, midi2) that I upload one by one. I am looking for something where I could combine midi1 and midi2 into one single midi file (say midi3) that when uploaded would show up as Track 1 and Track 2. Your solution combines midi1 and midi2 into a single track.

**Comment by GavinRay97** [comment]
@saatsochyaasi If you use @olemb's snippet, you'll get a single ".mid" file that contains multiple instrument tracks.

When you import in your DAW, most of them (I think?) give you the option to explode the MIDI file tracks into individual tracks in the arranger, or to keep them as a single combined kit.

---

Thank you @olemb for that snippet, I was able to use that to figure out how to do this same thing.

If anyone is curious, here is an example script that takes a directory full of folders of drumkit individual instrument ".mid" files (Ableton style, where they're all mapped to Middle C on Channel 1) and combined them into General MIDI Percussion spec-ish compliant combined ".mid" files (both multi-track and single-track). It starts with the "kick" file on note 36 and then just alphabetically assigns upwards from there.

https://gist.github.com/GavinRay97/91607cb04846ea12424d96dda66abed0

(You may be able to re-use the single-track variant here @saatsochyaasi if that's what you wanted exactly)

Found that you can just do this to freely convert from multi-track combined MIDI -> single-track merged MIDI:

```py
# This is single-track merged MIDI, versus multi-track merged MIDI that is created from combined_midi
merged_midi = MidiFile()
merged_midi.tracks.append(merge_tracks(combined_midi.tracks))
```

**Comment by vvanhee** [comment]
Is there a way to merge two midi tracks in the same midi file into one track? I have quite a few midi files with two counterpoint melodies that I'd like to merge together into one track (for processing with tensorflow magenta polyphony).

**Comment by Gnai** [comment]
> Is there a way to merge two midi tracks in the same midi file into one track? I have quite a few midi files with two counterpoint melodies that I'd like to merge together into one track (for processing with tensorflow magenta polyphony).

@vvanhee did you find any solution for that? Thanks :)

**Comment by vvanhee** [comment]
Sorry, I never figured this out
