### ISSUE TITLE
Sync issue with MIDI / WAV files

### ISSUE THREAD

**Issue by eric-yates** [mido/mido#245]
Hello! I need to play a MIDI file (using mido) and WAV file (using [pysimpleaudio](https://github.com/hamiltron/py-simple-audio)) at the _exact_ same time. The MIDI file is dragging relative to the WAV file. It seems as if the MIDI is playing ever so slightly too slow, which leads to the files becoming out of sync. Here's some details:

* WAV sample_rate = 44.1 kHz
* MIDI ticks_per_beat = 96
* MIDI tempo = 120 bpm (I believe? There is no set_tempo in MIDI file)

Files:

* [Archive.zip](https://github.com/mido/mido/files/5399265/Archive.zip)

Any idea what's going on here?

**Information to replicate:**

I'm using multiprocessing with one Process for the MIDI file and another Process for the WAV file. Each Process waits until an agreed upon start time to execute, which confirms that the play() methods for each are being called at the same timestamp to the microsecond.

The full code is at the bottom. I've verified that the following two calls are started at the exact same timestamp to the microsecond:

```py
for msg in mid_file.play():
        mid_port.send(msg)
```

```py
play_file = wav_file.play()
play_file.wait_done()
```

**System info:**

* Windows 10 (ugh)
* Python 3.7

**Code (truncated for brevity):**

```py
from multiprocessing import Process
from time import time

import simpleaudio as sa
import mido


MID_PORT_NAME = ...
mid_port = mido.open_output(MID_PORT_NAME)


class AudiovisualClient:

    def __init__(self):
        self.procs = []
        self.mid_path = None
        self.wav_path = None
        self.mid_file = None
        self.wav_file = None

    def run_files(self, mid_path, wav_path):

        self.mid_path = mid_path
        self.wav_path = wav_path
        self.mid_file = mido.MidiFile(self.mid_path)
        self.wav_file = sa.WaveObject.from_wave_file(self.wav_path)

        start_time = time() + 3  # Start each Process at agreed upon time

        self.procs = [
            Process(target=start_connect_audio, args=(self.wav_file, start_time)),
            Process(target=start_connect_visual, args=(self.mid_file, start_time)),
        ]

        for proc in self.procs:
            proc.start()


def start_connect_audio(wav_file, start_time=None, delay=0):
    if start_time is not None:
        while time() < start_time + delay:
            pass
    play_file = wav_file.play()
    play_file.wait_done()


def start_connect_visual(mid_file, start_time=None):
    if start_time is not None:
        while time() < start_time:
            pass
    for msg in mid_file.play():
        mid_port.send(msg)
```

**Usage:**

```py
avc = AudiovisualClient()

mid_path = ...
wav_path = ...

avc.run_files(mid_path, wav_path)
```

**Comment by olemb** [comment]
Thank you for a very detailed bug report with example code and files!

When I wrote the file player I didn't take into account the time spent processing the messages. This is likely why the playback drags.

@belm0 had submitted a fix for this in pull request #161. Can you try the latest version in the master and see if the timing improves?
