### ISSUE TITLE
Mido inside Reaper

### ISSUE THREAD

**Issue by betov75** [mido/mido#246]
Hi! First of all, thank you very much for that fantastic library. So intelligently designed to make MIDI use in Python easy.
Is there a way I can use Mido inside a Reaper's python script? Making sure that the used ports are not shared by both applications? I've tried to import it but it was unsuccesful. I'm very new to Python (3 days) and I may not know how to link the library in my Reaper's Python script.
Thanks a lot!

**Comment by olemb** [comment]
I am happy to hear that you're enjoying Mido!

I'm not familiar with Reaper but it seems to have a pretty extensive Python API:

    https://www.reaper.fm/sdk/reascript/reascripthelp.html

There are a lot of functions named something with `MIDI` here.  `RPR_StuffMIDIMessage` looks like a good place to start experimenting. If I've read the docs correctly this should play a (very short) note on the virtual keyboard queue:

```
import mido

VKB = 0

msg = mido.Message('note_on', note=60)
RPR_StuffMIDIMessage(VKB, *msg.bytes())

msg = mido.Message('note_off', note=60)
RPR_StuffMIDIMessage(VKB, *msg.bytes())
```

You may have to import the `PRP_StuffMIDIMessage()` function first.

**Comment by olemb** [comment]
I don't know if the Mido ports will collide with the Reaper ports. The easiest way to find out is to just open a Mido port and see what happens.

Some programs will hog the port while others share. It depends on the API they use and how they use it.

**Comment by betov75** [comment]
Hi! Thank you VERY much for your very detailed and extremely useful answer. Please forgive me for the late return. I love Mido, it helped me create a (humbly) fantastic accessibility tool for blind musicians. In the end, I used OSC from REAPEER to access everything I needed. Your hint on VKB in scripting is a central part for a new idea that i'll put in my code so once again, thank you very much for your research on it.

My next step, using Mido, creating an arpeggiator specifically designed for the blind.

I'm taking the liberty of closing the issue, i'm new to Github and I don't know if it's a good practice to do it myself.

Have a great day!
