### ISSUE TITLE
Add key signature, time signature, and tempo to file

### ISSUE THREAD

**Issue by xhevahir** [mido/mido#251]
Hi, I have what seems to be a pretty simple task, but I'm having a hard time figuring out how to accomplish it: I want to set the key signature, tempo (given a bpm), and time signature of an existing MIDI file which does not have any of those MetaMessages. (The file is MIDI type 0 at time of import, btw.) Thanks for any pointers.

**Comment by xhevahir** [comment]
Sorry. Posting to Google group instead.

**Comment by xhevahir** [comment]
Reopening issue because the Google Group has apparently been deactivated?

**Comment by xhevahir** [comment]
So at this point I realize that time signatures can't simply be added to an existing MIDI file, but I'm still wondering how to add a key signature, since that seems like it *should* be a simpler thing to do.

**Comment by olemb** [comment]
I'm not sure why you can't access the google group. I'll look into it.

A type 0 file has only one track. If you you want the time signature and tempo to be the same for the whole file you can add them to the beginning of the track with something like:

```
from mido import MidiFile, MidiTrack, MetaMessage

mid = MidiFile('test.mid')
track = mid.tracks[0]

track.insert(0, MetaMessage('key_signature', key='C'))
track.insert(0, MetaMessage('set_tempo', tempo=250000))

mid.save('out.mid')
```

If you want the tempo and key signature to vary you will need to find

**Comment by xhevahir** [comment]
Thanks!
