### ISSUE TITLE
Move automated testing from Travis to GitHub Actions

### ISSUE THREAD

**Issue by bast** [mido/mido#266]
Working on a PR ...

**Comment by bast** [comment]
My plan:
- add GH Actions (but do not remove the rest)
- observe it for few days
- only later remove .travis.yml, tox.ini, and the Travis badge

**Comment by bast** [comment]
Example: https://github.com/mido/mido/actions/runs/434433524

**Comment by olemb** [comment]
Nice!

Kind of look forward to some tests failing now so I can see what that looks like. :-D
