### ISSUE TITLE
Move roadmap to separate repository

### ISSUE THREAD

**Issue by olemb** [mido/mido#269]
The roadmap will always be ahead of the code so it should live in its own repository.

**Comment by olemb** [comment]
https://mozillascience.github.io/working-open-workshop/roadmapping/

**Comment by rdoursenaud** [comment]
I think we should use issues combined with the milestone feature of GitHub.

I've created a [Future](https://github.com/mido/mido/milestone/2) milestone that can hold any idea not planned for any version yet.

We can then migrate them into version milestones as we see fit.

It's a more flexible and collaborative approach than a static document we will undoubtedly forget to update and allows to put a good user-submitted feature request onto the roadmap quite easily.

**Comment by rdoursenaud** [comment]
If it's okay with you, I volunteer to port the current roadmap to this new system.
