### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by olemb** [mido/mido#270]
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

**Comment by bast** [comment]
Yes, this is very important.

**Comment by rdoursenaud** [comment]
I suggest that we take inspiration from the [Python Software Foundation's code of conduct](https://www.python.org/psf/conduct).

I'd also add it as `docs/code_of_conduct.rst` to keep things consistent with our existing `contributing.rst`.
The `/docs` folder is fully supported by GitHub as outlined in [their documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).

**Comment by bast** [comment]
Thanks for this good suggestion! Would you like me to add it?

**Comment by rdoursenaud** [comment]
@bast Go ahead if you feel like it!

**Comment by bast** [comment]
I will add it this weekend.
