### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by olemb** [mido/mido#272]
This is difficult to do at the moment but GitHub have promised to add a tool to make it easy by the end of the year.

**Comment by olemb** [comment]
They've pushed it off to January 2021:

https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-

**Comment by bast** [comment]
Taking the issue but I think this one should go first in: #283

**Comment by olemb** [comment]
#283 is merged.
