### ISSUE TITLE
Returned ssh Traceback? 

### ISSUE THREAD

**Issue by Logan-Orr** [mido/mido#314]
Is this return after booting up the pi normal? What concerns me is the import error, is this because I have not connected the Piano or LEDS?
<img width="560" alt="Screen Shot 2021-06-03 at 3 27 54 PM" src="https://user-images.githubusercontent.com/77374951/120720094-4eb0ce00-c480-11eb-966d-95e29e4a44da.png">

**Comment by olemb** [comment]
It looks like Mido is not installed correctly.

Could you make a `test.py` with the following and run it instead of `visualizer.py`:

```
import mido
from mido import MidiFile
```

Should give the same error message.

**Comment by rdoursenaud** [comment]
This seem to be coming from the great [Piano-LED-Visualizer][https://github.com/onlaj/Piano-LED-Visualizer] project.
Please seek help there.
We are only responsible for maintaining the mido library that they use.
