### ISSUE TITLE
Meta events decoding shouldn't assume size and check the file provided one

### ISSUE THREAD

**Issue by Rainbow-Dreamer** [mido/mido#358]
Hi, when I try to read some MIDI files, when some meta messages contains empty data and mido tries to get attributes from it, not all of the decode function of every type of meta messages has the boundary check for data to see if it is empty, and straightly get the data element by indexing as assuming the data is not empty, which causes index out of range error. This is a bug that should be fixed in the newest version of mido, although I think this situation does not happens very often in MIDI files, but there are special cases, as I have encountered. One example of when error happens and with the fixed code is here (with the `if data` you can ensure that you have boundary check for the data of the key signature meta messages and won't get wrong when the data is empty):
```python
class MetaSpec_key_signature(MetaSpec):
    type_byte = 0x59
    attributes = ['key']
    defaults = ['C']

    def decode(self, message, data):
        if data:
            key = signed('byte', data[0])
            mode = data[1]
            try:
                message.key = _key_signature_decode[(key, mode)]
            except KeyError:
                if key < 7:
                    msg = ('Could not decode key with {} '
                           'flats and mode {}'.format(abs(key), mode))
                else:
                    msg = ('Could not decode key with {} '
                           'sharps and mode {}'.format(key, mode))
                raise KeySignatureError(msg)
```
You can add `if data:` at the start of the decode function of each class of meta messages if there is no boundary check.

**Comment by rdoursenaud** [comment]
I can't quite understand when this situation arises.
Could you please provide a problematic file?

**Comment by Rainbow-Dreamer** [comment]
Sure, here is a MIDI file that I tested at that time which fails when reading the file, this MIDI file could be normally played by players that supports MIDI (including Windows Media Player) on Windows 10.
Here is the test code:
```python
import mido
current_file = mido.MidiFile('th08_10.mid')
```
[th08_10.zip](https://github.com/mido/mido/files/10460255/th08_10.zip)

**Comment by rdoursenaud** [comment]
Thank you for providing the file!

Here's what I get trying to open it in `debug` mode:
```py
Header:
  000008: 4d  M
  000008: 54  T
  000008: 68  h
  000008: 64  d
  000008: 00  .
  000008: 00  .
  000008: 00  .
  000008: 06  .
  00000e: 00  .
  00000e: 00  .
  00000e: 00  .
  00000e: 01  .
  00000e: 01  .
  00000e: e0  .
-> type=0, tracks=1, ticks_per_beat=480

Track 0:
  000016: 4d  M
  000016: 54  T
  000016: 72  r
  000016: 6b  k
  000016: 00  .
  000016: 00  .
  000016: c0  .
  000016: ef  .
-> size=49391

Message:
  000017: 00  .
-> delta=0
  000018: ff  .
  000019: 03  .
  00001a: 00  .
-> MetaMessage('track_name', name='', time=0)

Message:
  00001b: 00  .
-> delta=0
  00001c: ff  .
  00001d: 02  .
  00001e: 00  .
-> MetaMessage('copyright', text='', time=0)

Message:
  00001f: 00  .
-> delta=0
  000020: ff  .
  000021: 58  X
  000022: 04  .
  000023: 04  .
  000024: 02  .
  000025: 18  .
  000026: 08  .
-> MetaMessage('time_signature', numerator=4, denominator=4, clocks_per_click=24, notated_32nd_notes_per_beat=8, time=0)

Message:
  000027: 00  .
-> delta=0
  000028: ff  .
  000029: 59  Y
  00002a: 00  .
Traceback (most recent call last):
  File "G:\raph\Documents\GitHub\midiexplorer\src\midiexplorer\gui\helpers\smf.py", line 36, in _do_load
    mid = MidiFile(filename, clip=True, debug=DEBUG,
  File "mido\midifiles\midifiles.py", line 324, in __init__
    self._load(file)
  File "mido\midifiles\midifiles.py", line 359, in _load
    self.tracks.append(read_track(infile,
  File "mido\midifiles\midifiles.py", line 217, in read_track
    msg = read_meta_message(infile, delta)
  File "mido\midifiles\midifiles.py", line 172, in read_meta_message
    return build_meta_message(meta_type, data, delta)
  File "mido\midifiles\meta.py", line 460, in build_meta_message
    spec.decode(msg, data)
  File "mido\midifiles\meta.py", line 390, in decode
    key = signed('byte', data[0])
IndexError: list index out of range
```

The file is indeed malformed with a `Meta Event` (`0xff`) of type `Key Signature` (`0x59`) of length `0` instead of the expected `2` per specification.

I now see that mido isn't checking the length for correctness and erroneously tries to access data that does not exist.

I believe such a check should be implemented but it would (and should!) still raise some kind of `Exception`. This is something I can get behind.

On the other hand, we could have a mechanism to ignore such exceptions and try to parse the file to the best of our abilities like players do.

Is this what you meant?

**Comment by Rainbow-Dreamer** [comment]
Yes, indeed, we could read the MIDI files as much as we can as long as its file header is MThd (and RIFF-based MIDI files for better).

**Comment by sun123zxy** [comment]
Excuse me, I also come across this problem. The issue is closed but on my side it can still be reproduced in v1.3.3. Is it fixed in the current version?

**Comment by rdoursenaud** [comment]
I don't believe it is. If I recall correctly this is not something I can easily do with the current code and needs the refactoring I envisioned for v2.0. Unfortunately, due to still ongoing personal issues, I'm way behind schedule on this, sorry! I'll reopen the issue for now to not forget.
