### ISSUE TITLE
Cannot Receive Messages

### ISSUE THREAD

**Issue by jordanwolkon** [mido/mido#362]
Hello,

I am trying to run a simple script to receive MIDI messages and print them interactively. I've just copy and pasted the script from **examples/ports/receive.py** but I am unable to get any output while working with Ableton. The default port being used is **<open input 'Network Session 1' (RtMidi/MACOSX_CORE)>**, and I've also tried changing this manually to use IAC Driver by setting remote=True. Interestingly, when I set the port to IAC Driver with _GarageBand_ open (not Ableton), I do get one message printed that says **Received sysex data=(126,0,6,1) time=0**, but it will not print anything after that.

I am working on macOS Monterey Version 12.0.1. Sorry if I'm missing anything obvious here. Please let me know if there is any other information I can provide, and any help here would be greatly appreciated!

**Comment by r1yk** [comment]
This sounds like it might be an issue of having Ableton properly configured with your MIDI setup. One generic suggestion would be to follow the macOS instructions for [adding a new bus](https://support.apple.com/guide/audio-midi-setup/transfer-midi-information-between-apps-ams1013/mac) for the IAC Driver to use (maybe name the bus something easily recognizable like "Mido Test"), and then make sure that Ableton is sending its MIDI output to that bus.

From there, you may want to try the [list_ports](https://github.com/mido/mido/blob/main/examples/ports/list_ports.py) example, and make sure that Mido finds the new bus you created. Assuming it does, copy & paste the name of your new port provided by the IAC driver, and use that as your `portname` in your script. You probably want to explicitly specify the ports that Ableton + Mido are using, rather than relying on the system default.

**Comment by jordanwolkon** [comment]
Thank you for the quick response @r1yk! This worked perfectly - also for future readers, I realized that I further needed to configure my Ableton Input, Output, and Control Surface within **Live > Preferences > Link MIDI**.

Thanks again, really appreciate the help!

**Comment by r1yk** [comment]
Glad that worked out for you, and good luck with your project!

**Comment by jordanwolkon** [comment]
Apologies for reopening, but this seems to have randomly stopped working. I walked through the same steps as above, but am unable to produce any output from my control surface. I'm using the simple script below:

    try:
        with mido.open_input(name='IAC Driver (Mido Test)', virtual=True) as port:
            print('Using {}'.format(port))
            print('Waiting for messages...')
            for message in port:
                print('Received {}'.format(message))
                # sys.stdout.flush()
    except KeyboardInterrupt:
        pass

Here is how my configuration is set up in Ableton:

<img width="331" alt="midi_output" src="https://user-images.githubusercontent.com/68704750/158592615-8ed3195f-78fc-46e9-887a-80355a82e4b0.png">
<img width="488" alt="midi_config" src="https://user-images.githubusercontent.com/68704750/158592678-6c17ea71-7e7a-465c-a0ba-b0d01c8a7c43.png">

I noticed that when you route a control surface like MPK Mini to the driver it will change the name in the Ableton UI, but the outputs listed using mido.get_output_names() still show **IAC Driver Mido Test**. I also noticed that mido.get_output_names shows the names without parentheses while Ableton shows them with parentheses. I've tried inputting all three different named versions in my script, but none are producing output.

Any thoughts on what's going on here?

**Comment by rdoursenaud** [comment]
The `virtual=True` in the `mido.open_input()` statement seems odd to me.
Doing so creates a [virtual port](https://mido.readthedocs.io/en/latest/backends/rtmidi.html?highlight=virtual%3DTrue#virtual-ports).

If you intend to contact the IAC bus created as suggested by @r1yk, you should rather explicitly set the `virtual` parameter to `False` or omit it altogether (default value is `False`).

**Comment by jordanwolkon** [comment]
@rdoursenaud good call, thank you very much! Sorry that was pretty trivial, probably should've tested that out before reopening. Still curious why it was working before when I had `virtual=True`, but that's a question for another day...

Appreciate the quick response here!

**Comment by rdoursenaud** [comment]
Thanks! Glad I could be of help :)
