### ISSUE TITLE
Can only receive 1000 messages before input hangs

### ISSUE THREAD

**Issue by jackwilsdon** [mido/mido#37]
So I have modified the example [`examples/ports/input_filter.py`](https://github.com/olemb/mido/blob/8118d9e9a9a3431aa9cef53a64224309efc8ed05/examples/ports/input_filter.py) to filter for `clock` signals, however they seem to stop coming in after 1000 messages;

``` python
#!/usr/bin/env python
"""
Receive messages on the input port and print messages with a specific
channel (defaults to 0).
Usage:
    python example_input_filter.py portname [CHANNEL] [...]
"""

from __future__ import print_function
import sys
import mido

def accept_notes(port):
    """Only let clock messages through."""
    for message in port:
        if message.type == 'clock':
            yield message


if len(sys.argv) > 1:
    portname = sys.argv[1]
else:
    portname = None   # Use default port

try:
    with mido.open_input(portname) as port:
        print('Using {}'.format(port))

        print("Ignoring everything but 'clock'.")
        print('Waiting for notes...')

        counter = 0

        for message in accept_notes(port):
            counter += 1
            print('Received {} ({})'.format(message, counter))
except KeyboardInterrupt:
    pass
```

And here is the output from running that:

```
Received clock time=0 (1)
Received clock time=0 (2)
Received clock time=0 (3)
Received clock time=0 (4)
...
Received clock time=0 (999)
Received clock time=0 (1000)
```

The program then hangs on line 15 (`for message in port:`) forever.

I believe it's because of [this line (`mido/backends/portmidi.py:131`)](https://github.com/olemb/mido/blob/25b083ab6a98e85853bfdec9ff41e364195e3bf9/mido/backends/portmidi.py#L131), as the buffer size is set to 1000. After reading the documentation for [Pm_OpenInput](http://portmedia.sourceforge.net/portmidi/doxygen/group__grp__device.html#g2e778a55f5376c3ae19b943899adc36a), I'm not entirely sure why it's stopping at 1000.

The way I understand it is that the buffer fills up to a maximum of `bufferSize` events, while `Pm_Read` removes events from the buffer. This leads me to wonder why it's stopping as in theory the for loop should be emptying the buffer and allowing new messages to arrive.

Note that the clock messages are coming in _extremely_ fast, although I'm not entirely sure how fast.

Another interesting thing I've noticed is that the 1000 limit seems to only apply to the clock type message, as if I turn off the "clock filter" in that code, I get this at the start too:

```
Received sysex data=(126,127,6,1) time=0 (1)
Received sysex data=(126,0,6,1) time=0 (2)
Received sysex data=(0,32,127,3,1) time=0 (3)
Received start time=0 (4)
```

Which leads to me receiving 1003 notes instead of just 1000. What is going on?

**Comment by olemb** [comment]
That's strange.

I made this little test program to spam it with test messages:

```
import time
import mido

msg = mido.Message('clock')

outport = mido.open_output()
while True:
    outport.send(msg)
    # time.sleep(0.000001)                                                      
```

(In Linux/ALSA the default output loops back into the default input so I just run both with the default port.)

The same thing happens here except it stops at some random point between 1200 and 2000 messages. When I changed the buffer size to 10000 it stopped at about 10000 times that. "note_on"-messages get to about 5000 before they stop.

I inserted some prints into the PortAudio backend to see what's going on. It turns out pm.lib.Pm_Poll() just stops returning anything. It should return the number of available messages but it just starts returning 0 instead.

Could be a bug in PortAudio. It look like it just stops receiving messages if they come in too fast.

When I inserted the "time.sleep(0.000001)" it managed to keep up. That's a very short wait so I don't understand why it makes a difference.

I am curious though what device you have that's sending clock messages this often.

**Comment by olemb** [comment]
Update:

* I've tried on OSX. Same problem there.
* RtMidi (``MIDO_BACKEND=mido.backends.rtmidi ./receive.py``) keeps going but drops some messages and says "MidiInAlsa: message queue limit reached!!".
* I have made a few attempts to compile PortMidi so I could poke around a bit but ran into some problems compiling the Java bit.

**Comment by jackwilsdon** [comment]
@olemb It's the software Traktor set up to transmit down an IAC MIDI bus that mido is listening on. It's not sending them that often if I look at them using [MIDI Monitor](https://www.snoize.com/MIDIMonitor/), however they are being received almost instantly in mido which I find very peculiar. Could it be that Traktor is filling some form of MIDI buffer in the OS and mido is reading from the buffer, leading to insanely fast MIDI messages?

**Comment by rdoursenaud** [comment]
Yes, messages are usually buffered by the OS and/or driver implementations and stored/delivered in some kind of bulk.
I believe the rationale was to mitigate inefficiencies when there was (still sometimes is) hardware involved.
The behavior is **very** setup dependent.

Is it still relevant with the current version though?

**Comment by rdoursenaud** [comment]
I ran the provided sample code upon v.1.3.0 with rtmidi and portmidi backends.
It successfully received more than 10000 clock messages.

I guess it's fixed, so I'll close the issue for now.

Feel free to reopen if it wasn't the case for you.
