### ISSUE TITLE
'byref' Error when opening a port with PortMidi

### ISSUE THREAD

**Issue by tinkerlevu** [mido/mido#372]
Hi, I'm getting the error:

`AttributeError: module 'mido.backends.portmidi_init' has no attribute 'byref'`

when trying to open an output port with the portmidi backend. *(I'm using mido version 1.2.10)*

I fixed it by reverting *backends/portmidi_init.py* back to commit `bdc9249`

just a little heads up.

**Comment by brunoenten** [comment]
Submitted https://github.com/mido/mido/pull/383 to reverse this change.
