### ISSUE TITLE
Cannot connect to MIDI device with two identical MIDI USB VID PID

### ISSUE THREAD

**Issue by Erriez** [mido/mido#381]
I've two identical MIDI devices with the same MIDI USB VID and PID. One of the two devices is set into update mode and registers with a different set of MIDI input/output port names. Functions `mido.get_input_names()` and `mido.get_output_names()` returns an incorrect list of MIDI port names when both MIDI devices are connected to the computer.

**Python test script:**
```python
import mido

print(mido.get_input_names())
print(mido.get_output_names())
```

**Output:**
```
1. Connect first device A and run test script (Correct output):
    ['MyDevice 0']
    ['Microsoft GS Wavetable Synth 0', 'MyDevice 1']

2. Connect second device in update mode and run test script again (Correct output):
    ['MyDevice-update 0']
    ['Microsoft GS Wavetable Synth 0', 'MyDevice-update 1']

Connect first device, then second device in update mode and run script again (Incorrect output):
    ['MyDevice 0', 'MyDevice 1', 'MyDevice 1']
    ['MyDevice 1', 'Microsoft GS Wavetable Synth 0', 'MyDevice 1', 'MyDevice 2']
```

I can open MIDI ports on `MyDevice 1`, but not on `MyDevice-update x`. Is there a workaround or do I something wrong?

**Info**:
- Windows 10
- Mido: v1.2.10
- python-rtmidi: 1.4.9
- Python: v3.9.10

**Comment by Erriez** [comment]
This issue It looks like related to python-rtmidi and not mido:

**Python test script:**
```python
import rtmidi
from rtmidi import midiutil

midiout = rtmidi.MidiOut()
midiin = rtmidi.MidiIn()

available_ports_in = midiin.get_ports()
available_ports_out = midiout.get_ports()

print(available_ports_in)
print(available_ports_out)
```

**Output:**
```
['MyDevice 0', 'MyDevice 1']
['Microsoft GS Wavetable Synth 0', 'MyDevice 1', MyDevice 2']
```

**Comment by Erriez** [comment]
Closing issue as the problem is located in the MIDI backend and not `mido`.

**Comment by rdoursenaud** [comment]
Thanks.
Could you please link the upstream issue if you have reported it so we can eventually track progress and direct other impacted users.

**Comment by rdoursenaud** [comment]
Sorry, I'm dumb and didn't see you already kinda did it.
Please disregard my previous comment.
For reference, the `python-rtmidi° related issue is https://github.com/SpotlightKid/python-rtmidi/issues/111

**Comment by rdoursenaud** [comment]
Pretty far fetched comment: maybe it's even in rtmidi itself or OS dependent. Microsoft Windows has a tendency to scramble thing up with identical devices.
I unfortunately don't have access to two identical USB-MIDI devices as I would have liked to track down that bug.
Do you have access to another OS you may test your code with?

**Comment by Erriez** [comment]
> Do you have access to another OS you may test your code with?

Yes, my plan is to test with Ubuntu as well. I see the same behavior with REAPER, so maybe it is a problem in Windows.

**Comment by rdoursenaud** [comment]
Yeah, if Reaper behaves the same it's very probable it's in Windows' MME implementation.
I wonder if this is also present in the future UWP (aka RNtMidi) API.
You may be able to test it with BandLab's Cakewalk by setting it to `UWP` in the "Preferences > MIDI > Record and playback" menu.
The latest version of Steinberg Cubase also have it.

**Comment by Erriez** [comment]
It is not reproducible on Ubuntu 21.04:

**Setup virtualenv:**
```bash
$ sudo apt install python3-virtualenv libasound2-dev libjack-dev
$ virtualenv venv
$ source venv/bin/activate
$ pip install python-rtmidi
$ pip install cython
$ chmod +x rtmidi_test.py
$ ./rtmidi_test.py
```

**Python test code rtmidi_test.py:**
```python
#!/usr/bin/env python

import rtmidi
import time

midiout = rtmidi.MidiOut()
midiin = rtmidi.MidiIn()

while True:
    print(midiin.get_ports())
    print(midiout.get_ports())
    print()
    time.sleep(1)
```

**Output (correct)**:
```
Input ports:
  ['Midi Through:Midi Through Port-0 14:0', 'MyDevice:MyDevice MIDI 1 20:0', 'MyDevice-update:MyDevice-update MIDI 1 24:0']
Output ports:
  ['Midi Through:Midi Through Port-0 14:0', 'MyDevice:MyDevice MIDI 1 20:0', 'MyDevice-update:MyDevice-update MIDI 1 24:0']
```

No matter in which order the USB MIDI devices are connected/disconnected.

**Comment by Erriez** [comment]
> I wonder if this is also present in the future UWP (aka RNtMidi) API.

Do you have some test code?

> You may be able to test it with BandLab's Cakewalk by setting it to UWP in the "Preferences > MIDI > Record and playback" menu.
> The latest version of Steinberg Cubase also have it.

I cannot test these DAW's as I'm a REAPER user.

**Comment by rdoursenaud** [comment]
> Do you have some test code?

Unfortunately not.
I'm aware of an opened issue at rtmid: https://github.com/thestk/rtmidi/issues/145
and of a fork called [Libremidi][https://github.com/jcelerier/libremidi] that supports it amongst some other nice features but I'm not aware of any Python bindings for it yet.
I keep an eye on it though as I think it would be the perfect backend for a future mido version.

BandLab Cakewalk is free (modulo some personal informations) if you want to investigate further but I think it's clear the bug lies at the OS level and there's not much we can do about it right now.

**Comment by Erriez** [comment]
I've built this Windows C# MIDI example from source and works as expected:
https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/midi/

**Comment by rdoursenaud** [comment]
If you're able to build a similar resource for the WinMM API, we'd hopefully rest our case ;)

**Comment by rdoursenaud** [comment]
Just stumbled across that: https://gist.github.com/yoggy/1485181
Maybe enough.

**Comment by Erriez** [comment]
> BandLab Cakewalk is free (modulo some personal informations) if you want to investigate further but I think it's clear the bug lies at the OS level and there's not much we can do about it right now.

Also wrong MIDI port names.

**Comment by Erriez** [comment]
> Just stumbled across that: https://gist.github.com/yoggy/1485181 Maybe enough.

Thanks for your hint. Same problem with [updated source](https://gist.github.com/yoggy/1485181?permalink_comment_id=4234082#gistcomment-4234082). So the problem is located in the Windows API. I think research stops here.

**Comment by rdoursenaud** [comment]
Yup. Case closed.
Thanks again Microsoft and good luck getting that fixed.
I wouldn't even know where to begin to report this properly to them.…

Thanks for the ride! The more you know…

Hope you'll find a workaround for your use case.
