### ISSUE TITLE
dlsym(RTLD_DEFAULT, Pm_Initialize): symbol not found

### ISSUE THREAD

**Issue by DidierMalenfant** [mido/mido#384]
I'm on macOS 12.5.1-arm and I'm forced to upgrade to Python 3.11 because of another dependency on the project I'm working on. 

`python-rtmidi` unfortunately doesn't support 3.11 and error when compiling rtmidi.

When trying to switch to `PortMidi` (installed via brew), I choose the back end with:
```
mido.set_backend('mido.backends.portmidi')
```
but I get the following error when trying to use `mido`:
```
dlsym(RTLD_DEFAULT, Pm_Initialize): symbol not found
```
Any idea where I'm going wrong?

**Comment by rdoursenaud** [comment]
PortMidi is notoriously difficult to get working properly sometimes.
I'm not yet familiar enough with its intricacies to help out.

I'd try the `pygame` backend which uses a baked-in PortMidi.
