### ISSUE TITLE
clock message docs

### ISSUE THREAD

**Issue by nathan-stewart** [mido/mido#398]
I'm trying to send MIDI Clock signals and it's not clear from the docs what's going on. There's just one mention of clock and it takes no parameters, so I can't set data to F8/FA/FB/FC. I believe what I'm trying to do is send F8 as I'm trying to synchronize a clock on a remote device (effects unit).

What is going out when you send a Message ('clock')?

**Comment by rdoursenaud** [comment]
Hi and welcome to mido.
Your question would be better suited for the [discussions Q&A area](https://github.com/mido/mido/discussions/categories/q-a).
Issues are not the place for this.
Thanks.
