### ISSUE TITLE
Make the project REUSE compliant

### ISSUE THREAD

**Issue by rdoursenaud** [mido/mido#410]
See https://reuse.software/ for details.

The gist of the work is:
- [x] Convert all copyright headers in source code files to [SPDX](https://spdx.org/licenses/) compliant versions
- [x] Add `.license` files for all other files
- [x] Add the compliance requirement to our [contributing guidelines](https://github.com/mido/mido/blob/main/docs/contributing.rst)
- [x] Implement the [REUSE Compliance Check](https://github.com/marketplace/actions/reuse-compliance-check) in our GitHub Actions.

**Comment by olemb** [comment]
This seems useful. I'm just worried that the repository will be cluttered with .license files. Any thoughts @bast?

**Comment by rdoursenaud** [comment]
The only files I identified in mido that would require a `.license` file are:
- [mido.png](https://github.com/mido/mido/blob/main/logo/mido.png)
- [mido.svg](https://github.com/mido/mido/blob/main/logo/mido.svg)
- [midi_time.svg](https://github.com/mido/mido/blob/main/docs/images/midi_time.svg)

All other files are source code or allow some sort of comment where to place the SPDX statement.

I think its an acceptable tradeoff to make for licensing clarity.

**Comment by olemb** [comment]
Sounds good to me.

**Comment by olemb** [comment]
Should we use a Creative Commons license for these? I don't know if MIT makes sense for image files.

**Comment by rdoursenaud** [comment]
You're the copyright holder, you shall decide which license you see fit.
That being said, yes, a CC or CC-BY license would be more appropriate than the MIT.

**Comment by olemb** [comment]
CC-BY sounds about right. Is there one called "CC"? I couldn't find one.

**Comment by olemb** [comment]
I agree. We'll use CC-BY.

Aha, I didn't look for CC0. I thought there was one named "CC" but that's of course just the general term for Creative Commons so it wouldn't make sense.

**Comment by rdoursenaud** [comment]
It just occurred to me that the MIT isn't the best licence either for the documentation.
Should we also use the CC-BY-4.0?

ALso, what about using CC0 for configuration files which are not copyrightable since they are considered facts?

**Comment by rdoursenaud** [comment]
Since I was in the zone, I've gone ahead and did just that.
Don't fret letting me know if you want me to do something different.

**Comment by bast** [comment]
TIL about https://reuse.software/! Thanks for the good suggestion!
