### ISSUE TITLE
Inconsistent virtual port naming due to expand_alsa_port_name()

### ISSUE THREAD

**Issue by digitalsignalperson** [mido/mido#471]
I'm using https://github.com/velolala/touchosc2midi which uses mido to create a virtual in and out port like this:

```python
midi_in = backend.open_input("TouchOSC Bridge", virtual=True, callback=lambda x: x)
midi_out = backend.open_output("TouchOSC Bridge", virtual=True)
```
which results in 

print(midi_in) => `<open input 'TouchOSC Bridge' (RtMidi/LINUX_ALSA)>`
print(midi_out) => `<open output 'RtMidiIn Client:TouchOSC Bridge 129:0' (RtMidi/LINUX_ALSA)>`

As you can see, the first virtual port gets the name we expect, the 2nd gets "RtMidiIn" prepended, and "129:0" appended.

This confuses other software, in particular Mixxx will not see these two ports with different name patterns as one controller.

If in backends/rtmidi.py I comment out `if api == 'LINUX_ALSA': name = expand_alsa_port_name(rt.get_ports(), name)` then I get the expected result 

print(midi_in) => `<open input 'TouchOSC Bridge' (RtMidi/LINUX_ALSA)>`
print(midi_out) => `<open output 'TouchOSC Bridge' (RtMidi/LINUX_ALSA)>`

and in Mixxx I can use "TouchOSC Bridge" as my controller with both inputs and outputs working as expected.

In not sure what the pupose of expand_alsa_port_name() is here when creating a virtual port. 
Maybe the code in rtmidi.py:_open_port() should be like this

```python
    if api == 'LINUX_ALSA' and not virtual:
        name = expand_alsa_port_name(rt.get_ports(), name)
```

**Comment by rdoursenaud** [comment]
Thanks for the detailed report.

I'd suggest rewriting `backends/rtmidi.py _open_port()`:
```py
    if api == 'LINUX_ALSA':
        name = expand_alsa_port_name(rt.get_ports(), name)

    if client_name is not None:
        virtual = True

    if virtual:
        if name is None:
            raise OSError('virtual port must have a name')

        rt.open_virtual_port(name)
        return name
```

to

```py
   if client_name is not None:
        virtual = True

    if virtual:
        if name is None:
            raise OSError('virtual port must have a name')

        rt.open_virtual_port(name)
        return name

    if api == 'LINUX_ALSA':
        name = expand_alsa_port_name(rt.get_ports(), name)

```

I believe this would fix your issue without changing the current behavior for non-virtual ports.

Can you please confirm?

**Comment by digitalsignalperson** [comment]
Yes I can confirm that works.
