### ISSUE TITLE
mido.get_input_names() and mido.get_output_names() list IAC twice on macOS Ventura 13.3.1, Python 3.11.0

### ISSUE THREAD

**Issue by bwagner** [mido/mido#478]
`mido.get_input_names()` and `mido.get_output_names()` list [IAC](https://support.apple.com/guide/audio-midi-setup/transfer-midi-information-between-apps-ams1013/mac) twice, even though underlying `python-rtmidi` correctly lists IAC-Port only once.
```
>>> import mido
>>> mido.get_input_names()
['IAC-Driver Bus 1', 'IAC-Driver Bus 1']
>>> mido.get_output_names()
['IAC-Driver Bus 1', 'IAC-Driver Bus 1']
>>>
>>> import rtmidi
>>> rtmidi.MidiIn().get_ports()
['IAC-Driver Bus 1']
>>> rtmidi.MidiOut().get_ports()
['IAC-Driver Bus 1']
```
macOS Ventura 13.3.1
Python 3.11.0
python-rtmidi 1.4.9
mido 1.2.10

EDIT: This has apparently been fixed: Running the same code with the current github version (bff6bf2a8711e33782de5661ed5ccdffb0bb1688) returns the correct number of IAC ports (one each for input/output names).

**Comment by rdoursenaud** [comment]
Thank you for the report.
I think I've seen something similar on Windows a while ago. I'll try and investigate as soon as I get time to work on `mido` again.

**Comment by rdoursenaud** [comment]
Oh, I didn't see your edit!
Thanks for having checked against the development version.
I'll close the issue then.
Feel free to reopen if need be.

**Comment by nai-kon** [comment]
Hello. Thank you for this great project! 
When do you plan to release this fixed version on pypi?

**Comment by rdoursenaud** [comment]
> Hello. Thank you for this great project! When do you plan to release this fixed version on pypi?

Next release is planned in a few days: https://github.com/mido/mido/milestone/1
