### ISSUE TITLE
Remove obsolete Travis CI webhook?

### ISSUE THREAD

**Issue by rdoursenaud** [mido/mido#502]
There’s a failing hook for Travis CI configured on our project: https://github.com/mido/mido/settings/hooks

@bast, I believe it’s been setup by you and abandoned in favor of GitHub Actions. Is it safe to remove? Could you please do it if that’s ok?

Thanks!

**Comment by bast** [comment]
It is true that I removed it. I will delete the hook.

**Comment by bast** [comment]
Done.
