### ISSUE TITLE
I Expected mido open a midi file but report an error

### ISSUE THREAD

**Issue by GoodenoughPhysicsLab** [mido/mido#525]
**Describe the bug**
Expect the code to work but report an error:
```
Traceback (most recent call last):
  File "d:/physicsLab/src/myTest.py", line 4, in <module>
    mido.MidiFile("D:/midi/千本樱.mid")
  File "D:\physicsLab\src\venv\lib\site-packages\mido\midifiles\midifiles.py", line 321, in __init__
    self._load(file)
  File "D:\physicsLab\src\venv\lib\site-packages\mido\midifiles\midifiles.py", line 366, in _load
    clip=self.clip))
  File "D:\physicsLab\src\venv\lib\site-packages\mido\midifiles\midifiles.py", line 220, in read_track
    msg = read_message(infile, status_byte, peek_data, delta, clip)
  File "D:\physicsLab\src\venv\lib\site-packages\mido\midifiles\midifiles.py", line 133, in read_message
    raise OSError('data byte must be in range 0..127')
OSError: data byte must be in range 0..127
```
My music player and even PyGame played this midi properly, but the mido read failed

**Expected behavior**
Expect mido to be up and running

**Code Snippet**
If applicable, add a code snippet to help explain your problem.
```python
import mido
MidiFile("千本樱.mid")
```

**Context (please complete the following information):**
- Operating system name & version: Windows 7
- Python version: Python 3.7.8, Python 3.8.10
- mido package version (Retrievable using `mido.version_info`) & installation method (Distribution repository, PyPI, source…): v1.2.10, v1.3.0 installed from PyPI
- backend used (amidi, portmidi, rtmidi, PyGame…): python-rtmidi ???What's this, but I use pygame

**Comment by rdoursenaud** [comment]
Hi and welcome to mido,

This is not a bug.
Your MIDI file is probably not specification compliant.
You may be able to open it by passing `clip=True` to the MIDIFile constructor which clamps all values above 127 to 127:
```py
import mido
MidiFile("千本樱.mid", clip=True)
```

**Comment by GoodenoughPhysicsLab** [comment]
Thank you! It works.
