### ISSUE TITLE
MIDI file issue with python mido module

### ISSUE THREAD

**Issue by digital-cinema-arts** [mido/mido#576]
**Describe the bug**
I'm having trouble with the mido python module. When I try to simply copy one MIDI file to another the resulting MIDI file is twice as long in length (all the notes are twice their durations). My intention is to strip out specific continuous controller data but I cannot figure this out. Here's a super simple code example

**Expected behavior**
The newly created MIDI file should contain the same note lengths as the source MIDI file.

**Code Snippet**
```py
from mido import Message, MidiFile, MidiTrack

def copy_MIDI_File(midi_file):

    src_midi = MidiFile(midi_file)
    midi_file = MidiFile()
    for i, src_track in enumerate(src_midi.tracks):
        new_track = MidiTrack()
        print('Track {}: {}'.format(i, src_track.name))
    
        for msg in src_track:        
            new_track.append(msg)
                                           
        midi_file.tracks.append(new_track)
    
    midi_file.save('new_song.mid')
```

**To Reproduce**
Try the code sample above.

**Context (please complete the following information):**
- Operating system name & version: [e.g. Mac OS Monterey]
- Python version: [e.g. Python 3.9.1]
installed from PyPI

**Additional context**
This is an example of 2 MIDI files, the top one is the source file, the bottom is the file created after running the simple example above.

![EKCU9](https://github.com/mido/mido/assets/528750/d0a6c25e-6fdb-4ea6-b3ff-452b60fb7d9d)

**Comment by rdoursenaud** [comment]
Hi and thanks for using mido,

Your source file has a resolution that is different from MIDI files default.
You need to explicitly set the destination's object resolution when initializing it or you're mixing events with different frame of reference.
This information is in the `ticks_per_beat` field.

Usually you also want to transfer the `type` and `charset`.

```py
midi_file = MidFile(ticks_per_beat=src_midi.ticks_per_beat, type=src_midi.type, charset=src_midi.charset)
```
