### ISSUE TITLE
Impossible to create a chord with absolute start times

### ISSUE THREAD

**Issue by cainky** [mido/mido#583]
**Describe the bug**
In any midi editor its quite trivial to create a chord where each note starts at 0, so that each note in the chord plays at the same time.

However, when using mido and you specify the start time as 0 for each note, it seems to apply some relative time adjustment where each note always starts after the other note ends.

If there is an easy way around this I am open to suggestions because otherwise it becomes impossible to form a chord from what I can tell

**To Reproduce**
Run this code and import the midi file into any midi editor. Observe that each note does not start simultaneously but sequentially even though all start times are set to 0.

```python
import mido

# Create a new MIDI file
mid = mido.MidiFile()

# Create a new track
track = mido.MidiTrack()
mid.tracks.append(track)

# Add notes with start time 0 and end time 480 (1 beat)
# Note 1
track.append(mido.Message('note_on', note=60, velocity=100, time=0))
track.append(mido.Message('note_off', note=60, velocity=100, time=480))
# Note 2
track.append(mido.Message('note_on', note=62, velocity=100, time=0))
track.append(mido.Message('note_off', note=62, velocity=100, time=480))
# Note 3
track.append(mido.Message('note_on', note=64, velocity=100, time=0))
track.append(mido.Message('note_off', note=64, velocity=100, time=480))

# Save the MIDI file
mid.save('output.mid')
```

**Expected behavior**
Each note in the chord to start at 0 time, rather than each note starting after each other. The absolute time of each note should be preserved and not adjusted based on previous notes starting times.

**Code Snippet**
Provided above

**Context (please complete the following information):**
Using the latest mido version.

**Additional context:**
This behavior limits the usability of the library for compositions requiring precise timing of simultaneous notes, such as chords, in MIDI music production.

**Comment by rdoursenaud** [comment]
Hi!

Thank you for trying out mido and for the detailed report.
Unfortunately, I'm unable to reproduce the behavior.

Running the code snippet you provided, I get the following file: [583.zip](https://github.com/mido/mido/files/15058093/583.zip)
Its analysis yields the expected result:
![mido-583-results](https://github.com/mido/mido/assets/1210367/1763a7b2-9324-4c9b-9fbd-755fda8ede84)

Could you please:
1. try the attached file with your DAW to clear out an issue on their end.
2. if the file is correct, upload an incorrect midi file (You have to zip it for GitHub to accept the attachment).

Thanks.

**Comment by cainky** [comment]
Hi @rdoursenaud , appreciate your prompt response and help. I have tried multiple DAWs and all experience the same issue. I imported your attached file into Ableton and this is what I see , as you can see all the notes should start at time 0 but they seem to be offset to start one after the other, which doesn't yield the intended result -- which would be all notes starting at the same time
![midi_offset](https://github.com/mido/mido/assets/22282320/50fa41d9-41de-4e01-ae64-e64f0f191453)

**Comment by cainky** [comment]
When exporting a MIDI file from ableton that I created with all start times of 0 you can see there is a difference in the total_times column 
![track0](https://github.com/mido/mido/assets/22282320/57c31ad2-088a-49c2-b062-06d155cae628)
[Track 0.zip](https://github.com/mido/mido/files/15134997/Track.0.zip)

versus our exported file from mido
![583](https://github.com/mido/mido/assets/22282320/f97254c5-01e8-4ec4-8672-ec5de34a10a4)

**Comment by rdoursenaud** [comment]
Oh! I see what's going on. Time is a delta time since the last `note_off`. Rewriting your code to the following should fix the issue. (Can't test right now.)
```py
import mido

# Create a new MIDI file
mid = mido.MidiFile()

# Create a new track
track = mido.MidiTrack()
mid.tracks.append(track)

# Add notes with start time 0 and end time 480 (1 beat)
# Notes on
track.append(mido.Message('note_on', note=60, velocity=100, time=0))  # Note 1
track.append(mido.Message('note_on', note=62, velocity=100, time=0))  # Note 3
track.append(mido.Message('note_on', note=64, velocity=100, time=0))  # Note 2
# Notes off
track.append(mido.Message('note_off', note=60, velocity=100, time=480))  # Note 1
track.append(mido.Message('note_off', note=62, velocity=100, time=480))  # Note 2
track.append(mido.Message('note_off', note=64, velocity=100, time=480))  # Note 3

# Save the MIDI file
mid.save('output.mid')
```

**Comment by cainky** [comment]
Legend! Thank you that fixes it :)

**Comment by rdoursenaud** [comment]
Good to hear!

I'll make sure to clean up the API in version 2 to make it obvious when time is absolute or relative and allow both approaches for event creation.
